create database Retail_Data_Analysis

use Retail_Data_Analysis

select * from customer

select * from prod_cat_info

select * from tbl_tran

-- DATA PREPARATION AND UNDERSTANDING

-- 1. What is the total number of rows in each  of the 3 tables in the database?

select count(customer_id) from customer

select count(prod_cat_code) from prod_cat_info

select count(transaction_id) from tbl_tran

-- 2. What is the total number of transactions that have a return?

select count(transaction_id) from tbl_tran
where qty < 0

-- 4. What is the time range of transaction data available for analysis? Show the output in number of days, months and 
-- years simultaneously in different columns. 	

select day(tran_date) 'Day', month(tran_date) 'Month', year(tran_date) 'Year' from tbl_tran 
order by tran_date asc

-- 5. Which product category does the sub-category "DIY" belong to?

select prod_cat, prod_subcat from prod_cat_info
where prod_subcat = 'DIY'

-- DATA ANALYSIS

-- 1. Which channel is most frequently used for transactions?

select top 1 store_type, count(store_type) from TBL_TRAN
group by Store_type
order by count(store_type) desc


--2. What is the count of male and female customers in database?

select Gender, count(gender) from Customer
where gender in ('m', 'f')
group by gender


--3. From which city do we have the maximum customers and how many?

select top 1 city_code,  count(city_code) from customer
group by city_code
order by count(city_code) desc

--4. How many sub-categories are there under the Books category? 

select prod_cat, count(prod_subcat) from prod_cat_info
where prod_cat = 'books'
group by prod_cat

--5. What is the maximum quantity of products ever ordered?

--If question is asking maximum quanity ordered in a single day

select top 1 tran_date, sum(qty) from TBL_TRAN
where qty > 0
group by tran_date
order by sum(qty) desc

--If question is asking maximum quanity ordered in a single transaction

select top 1 transaction_id, sum(qty) from TBL_TRAN
where qty > 0
group by transaction_id
order by sum(qty) desc



--6. What is the total revenue generated in books and electronics?

select sum(total_amt) from TBL_TRAN inner join prod_cat_info on TBL_TRAN.prod_cat_code = prod_cat_info.prod_cat_code AND TBL_TRAN.prod_subcat_code= prod_cat_info.prod_sub_cat_code
where prod_cat in ('books', 'Electronics') and total_amt > 0 



-- 7. How many customers have > 10	transactions with us, excluding returns?		

select cust_id, count(transaction_id) 'Count' from tbl_tran
where total_amt > 0
group by cust_id
having count(transaction_id) > 10 
order by count(transaction_id) desc

select * from TBL_TRAN



--8. What is the combined revenue earned from the 'Electronics' & 'Clothing'categories from 'Flagship store'?

select sum(total_amt) from tbl_tran inner join prod_cat_info on TBL_TRAN.prod_cat_code = prod_cat_info.prod_cat_code AND TBL_TRAN.prod_subcat_code= prod_cat_info.prod_sub_cat_code
where prod_cat in ('Electronics' , 'Clothing') and  Store_type = 'Flagship store' and total_amt > 0


-- 9. What is the total revenue generated by 'Male' customers in 'Electronics' category? Output should display total revenue
--    by prod sub-cat. 


select prod_subcat AS ProductSubcategory,sum(total_amt) as TotalRevenue
from tbl_tran T1 LEFT join Customer on cust_id = customer_Id INNER join prod_cat_info on T1.prod_cat_code = prod_cat_info.prod_cat_code AND T1.prod_subcat_code= prod_cat_info.prod_sub_cat_code
where  gender = 'm' and t1.prod_cat_code = 3  and t1.total_amt > 0 and t1.total_amt in (select total_amt from TBL_TRAN T2 , prod_cat_info where T1.prod_subcat_code = T2.prod_subcat_code)
group by prod_subcat



--10. What is the percentage of sales and returns by product sub category; display only 5 sub-categories in terms of sales?

select top 5 prod_subcat, (sum(total_amt)/(select sum(total_amt) from tbl_tran where total_amt > 0))*100 as Sales, (sum(total_amt)/(select sum(total_amt) from tbl_tran))*100 as 'Returns'
from TBL_TRAN T2 inner join prod_cat_info on T2.prod_cat_code = prod_cat_info.prod_cat_code AND T2.prod_subcat_code= prod_cat_info.prod_sub_cat_code
group by prod_subcat
order by Sales desc

--11. For all customer aged between 25 to 35 years find what is the total revenue generated by these consumers in last 30 days
--	  of transactions from the max transaction date available in the data?

select cust_id,  DATEDIFF(yy, dob, MAX(tran_date)) as AGE, SUM(total_amt) TOTAL_REV
 from customer inner join TBL_TRAN on customer_Id = cust_id
where total_amt > 0
 group by DOB, tran_date, cust_id
having tran_date between DATEADD(mm, -1, max(tran_date)) and MAX(tran_date)  
	   and DATEDIFF(yy, dob, MAX(tran_date)) between 25 and 35
order by DATEDIFF(yy, dob, MAX(tran_date))

-- 12. Which product category has seen the max values of returns in the last 3 months of transactions?

select top 1 prod_cat, sum(total_amt) as 'Returns' 
from TBL_TRAN inner join prod_cat_info on TBL_TRAN.prod_cat_code = prod_cat_info.prod_cat_code AND TBL_TRAN.prod_subcat_code=prod_cat_info.prod_sub_cat_code
where total_amt < 0                 
group by prod_cat, tran_date
having tran_date between DATEADD(mm, -3, max(tran_date)) and MAX(tran_date) 
order by sum(total_amt)


--13. Which store type sells the maximum products, by value of sales amount and by quantity sold?

select top 1 Store_type, sum(qty) QuantitiesSold, (sum(total_amt) - sum(tax)) TotalSales 
from TBL_TRAN
where total_amt > 0
group by Store_type
order by sum(qty) desc

-- 14. What are the categories for which average revenue is above the overall average?

select PROD_CAT ProductCategory, AVG(TOTAL_AMT) AverageRevenue
 from TBL_TRAN LEFT JOIN PROD_CAT_INFO ON TBL_TRAN.PROD_CAT_CODE = PROD_CAT_INFO.PROD_CAT_CODE AND TBL_TRAN.prod_subcat_code = prod_cat_info.prod_sub_cat_code
					where total_amt > (select avg(total_amt) from TBL_TRAN ) 
					GROUP BY PROD_CAT
					order by AVG(TOTAL_AMT) desc

-- 15. Find the average and total revenue by each sub-category for the categories which are among top 5 categories in
--	   terms of quantity sold.

select  prod_subcat ProductSubcategory, avg(total_amt) as AverageSales, sum(total_amt) as TotalSales
from TBL_TRAN t inner join prod_cat_info on t.prod_cat_code = prod_cat_info.prod_cat_code AND t.prod_subcat_code = prod_cat_info.prod_sub_cat_code
where total_amt > 0 and t.prod_cat_code in (SELECT TOP 5 t1.prod_cat_code
											from TBL_TRAN t1 inner join prod_cat_info on t1.prod_cat_code = prod_cat_info.prod_cat_code AND t1.prod_subcat_code = prod_cat_info.prod_sub_cat_code
										GROUP BY t1.prod_cat_code
										order by sum(qty) desc)
group by prod_subcat
